services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recruiter_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000
    env_file:
      - ./backend/.env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  queue:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: recruiter_queue
      working_dir: /var/www
      volumes:
      - ./backend:/var/www
      depends_on:
      - mysql
      command: php artisan queue:work --tries=3 --timeout=90
      env_file:
      - ./backend/.env
      environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      restart: unless-stopped
      
  mysql:
    image: mysql:8.4
    container_name: recruiter_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: recruiter_platform
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: