name: Deploy to AWS

on:
  push:
    branches:
      - main
      - feature/github-actions-cicd

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node 20 explicitly
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected successfully 🚀"
            hostname
            pwd
